name 'jlyheden-pam'
version '0.0.1'
author 'Johan Lyheden'
license 'Apache License 2.0'
project_page 'https://bitbucket.org/jlyheden/puppet-pam'
source 'git@bitbucket.org:jlyheden/puppet-pam.git'
summary 'PAM management'
description 'A Puppet module for managing PAM'
dependency 'puppetlabs/stdlib', '>=3.2.0'
dependency 'ripienaar/concat', '>=0.2.0'
