name 'artisol-pam'
version '0.0.1'

author 'Johan Lyheden'
license ''
project_page 'https://bitbucket.org/jlyheden/puppet-pam'
source 'git@bitbucket.org:jlyheden/puppet-pam.git'
summary 'Puppet module for managing PAM'
description ''
dependency 'puppetlabs/stdlib', '==3.2.0'
