name 'jlyheden-pam'
version '0.0.2'
author 'Johan Lyheden'
license 'Apache License 2.0'
project_page 'https://github.com/jlyheden/puppet-pam'
source 'git@github.com:jlyheden/puppet-pam.git'
summary 'PAM management'
description 'A Puppet module for managing PAM'
dependency 'puppetlabs/stdlib', '>=2.6.0'
dependency 'ripienaar/concat', '>=0.2.0'
